theme: jekyll-theme-hacker
google_analytics: UA-154429886-2
title: PassiveCash.xyz
description: Ways to earn passive cash
show_downloads: "false"
include: [".well-known"]
social-network-links:
  email: "stephen@passivecash.xyz"
  twitter: passivecashxyz
