#theme: jekyll-theme-hacker
remote_theme: b2a3e8/jekyll-theme-console
google_analytics: G-Q203YEXP0D
title: PassiveCash.xyz
description: Passive Cash Ideas
show_downloads: "false"
include: [".well-known"]
